---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by minssogi2.
--- DateTime: 2023/02/27 4:24 PM
---
local unit_table = {}
unit_table[1] = 1
unit_table[2] = 60
unit_table[3] = 300
unit_table[4] = 1800
unit_table[5] = 3600
unit_table[6] = 43200
unit_table[7] = 86400
unit_table[8] = 604800
unit_table[9] = 2592000

local value = 1.60

local request_count = math.floor(value)
print('request_count : ' .. request_count)

local unit = math.floor(value % request_count * 10)
print('unit : ' .. unit_table[unit])

local value_str = "50.2"
local parts = {}
for part in string.gmatch(value_str, "[^.]+") do
    table.insert(parts, part)
end

print(parts[1])
print(parts[2])

