---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by minseok.
--- DateTime: 2023/02/26 5:31 PM
---

function add_two_numbers(a, b)
    return a + b
end

local result = add_two_numbers(1, 2)

print(result)